name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Specify the .NET version you're using

      - name: Restore dependencies
        run: dotnet restore './Ui/Ui.csproj'

      - name: Build the project
        run: dotnet build './Ui/Ui.csproj' --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish './Ui/Ui.csproj' --configuration Release --output ./publish --no-build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish/wwwroot
